services:
  nifi:
    image: apache/nifi:1.21.0
    container_name: nifi
    user: root
    ports:
      - 8080:8080
    networks:
      - kafka-network
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_data:/opt/nifi/nifi-current/data

  app_producer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: producer
    env_file:
      - .env
    networks:
      - kafka-network
    command: python3 producer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  app_consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: consumer
    env_file:
      - .env
    networks:
      - kafka-network
    command: python3 consumer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 1

volumes:
  nifi_logs:
  nifi_data:

networks:
  kafka-network:
    external: true