services:
  app_producer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
     - kafka-network
    command: python3 producer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  app_consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
     - kafka-network
    command: python3 consumer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 1

networks:
  kafka-network:
    external: true