services:
  zookeeper:
   image: confluentinc/cp-zookeeper:7.4.4
   container_name: zookeeper
   hostname: zookeeper
   ports:
     - 2181:2181
   networks:
     - kafka-network
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2

  nifi:
    image: apache/nifi:latest
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  app_producer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
     - kafka-network
    command: python3 producer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  app_consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
     - kafka-network
    command: python3 consumer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 1
