services:
  nifi:
      image: apache/nifi:1.21.0
      container_name: nifi
      user: root
      ports:
        - 8080:8080
      networks:
        - confluent
      environment:
        NIFI_WEB_HTTP_PORT: 8080

  app_producer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
     - kafka-network
    command: python3 producer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  app_consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    networks:
     - kafka-network
    command: python3 consumer.py
    restart: always
    deploy:
      mode: replicated
      replicas: 1

networks:
  kafka-network:
    external: true